export const INITIAL = 'INITIAL'
export const INITIAL_WITH_DATA = 'INITIAL_WITH_DATA'
export const CALCULATE_FEE_STEP = 'CALCULATE_FEE_STEP'
export const TRANSFER_INSTRUCTIONS_STEP = 'TRANSFER_INSTRUCTIONS_STEP'
export const SET_ACC_SYMBOL = 'SET_ACC_SYMBOL'
export const SET_EVM_SYMBOL = 'SET_EVM_SYMBOL'
export const SET_SEND = 'SET_SEND'
export const SET_SEND_AND_RECEIVING = 'SET_SEND_AND_RECEIVING'
export const GET_FEES = 'GET_FEES'


